#!/bin/bash
/var/pub/pyenv/bin/gfwlist2pac -f /var/www/pub/socks1314.pac -p 'SOCKS 127.0.0.1:1314' --user-rule /var/www/pub/config.txt
/var/pub/pyenv/bin/gfwlist2pac -f /var/www/pub/http1315.pac -p 'PROXY 127.0.0.1:1315' --user-rule /var/www/pub/config.txt
