#!/bin/bash
source /var/pub/py/bin/activate
/var/pub/py/bin/gfwlist2pac -f /var/pub/socks1314.pac -p 'SOCKS 127.0.0.1:1314' --user-rule /var/pub/config.txt
/var/pub/py/bin/gfwlist2pac -f /var/pub/http1315.pac -p 'PROXY 127.0.0.1:1315' --user-rule /var/pub/config.txt
